export default {
  title: "light",
  colors: {
    li: "#ffff",
    text: "#0d0d0d",
    inputColor: "#333",
    inputPlaceholder: "#000000",
    strongSchedule: "#020202",
    appointmentBackground: "#ffff",
    dayPicker: "#fff",
    dayAvailableBackground: "#E5E5E5",
    dayAvailableBackgroundHover: "#efefef",
    background: "#F0F0F7",
    primaryLighter: "#9871F5",
    primaryLight: "#916BEA",
    primary: "#8257E5",
    primaryDark: "#774DD6",
    primaryDarker: "#6842c2",
    secondary: "#04D361",
    secondaryDark: "#04BF58",
    titleInPrimary: "#FFFFFF",
    textInPrimary: "#D4C2FF",
    textTitle: "#f5f6ff",
    textComplement: "#9C98A6",
    textBase: "#6A6180",
    lineInWhite: "#E6E6F0",
    inputBackground: "#F8F8FC",
    buttonText: "#FFFFFF",
    boxBase: "#FFFFFF",
    boxFooter: "#FAFAFC",
    smallInfo: "#C1BCCC",
    productBackground: "#222748",
  },
};
